datasource:
  driver-class-name: "org.postgresql.Driver"
  url: "jdbc:postgresql://postgresql:5430"
  username: "local"
  password: "local"


volume-path:
  # for windows
#  persistent-volume-data: "C:\\volume\\local\\pv\\"
#  pod-volume-data: "C:\\volume\\local\\pod\\"

  # for mac
  persistent-volume-data: "/Volumes/Workspaces/workspace/projects/Study/K8s/kubernetes-anotherclass-api-tester/pv/"
  pod-volume-data: "/Volumes/Workspaces/workspace/projects/Study/K8s/kubernetes-anotherclass-api-tester/pod/"
