# 환경별 application.yaml 파일
spring:
  profiles:
    active: local
  # App 종료시
  lifecycle:
    timeout-per-shutdown-phase: 30s  #default 30s

# App Port
server:
  port: 8080
  shutdown: graceful

# App 정보
application:
  role: "ALL"
  version: "Api Tester v3.0.0"

# Database 접속 정보 위치 (Secret으로 주입)
postgresql:
  filepath: "/usr/src/myapp/datasource/postgresql-info.yaml"

# Database 접속 정보
datasource:
  driver-class-name:
  url:
  username:
  password:

# Volume 위치
volume-path:
  persistent-volume-data: 
  pod-volume-data:

# Pod 정보 파일 (Pod의 Volume과 env로 주입)
downward:
  volume:
    filepath:
  env:
    pod-name:
    pod-ip:
    node-name:
termination:
  message-path:

# kube-apiserver 정보 (Secret으로 주입)
api-token:
  url: "https://kubernetes.default"
  filepath: